const ActionTypes = {
  UPDATE_LOADING: "UPDATE_LOADING",
  GET_ITEMS: "GET_ITEMS",
  GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILURE: "GET_ITEMS_FAILURE",
  ITEMS_FILTER_CHANGE: "ITEMS_FILTER_CHANGE",
  ADD_ITEM: "ADD_ITEM",
  INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
  DECREMENT_QUANTITY: "DECREMENT_QUANTITY"
};

export default ActionTypes;
